package controller.command;

public enum Type {
    LOGIN_PAGE,
    REGISTER_PAGE,
    REPORT_PAGE,
    EDIT_PAGE,
    VIEW_PAGE,
    CHECK_PAGE,
    LOGOUT,
    CLIENT_CABINET,
    INSPECTOR_CABINET,
    ACCESS_DENIED,
    LANGUAGE_CHANGE,
    REPORT_VIEW,
    REPORT_EDIT,
    LOGIN,
    REGISTER,
    ABOUT_US,
    AJAX,
    CREATE_REPORT,
    REPORT_CHECK,
    PAGE_REQUEST_ADD,
    PAGE_REQUEST_SHOW,
    REQUEST_ADD,
    REQUEST_SHOW,
    PAGE_ACESS_DENIED
}
